### ISSUE TITLE
Typos in comments

### ISSUE THREAD

**Issue by CSOleson** [RIConeorg/API-ClientLibrary-DotNet#3]
The following 7 files have typos in the comments. I cannot create a branch/open a PR against the codebase to fix myself. If you want to give me access to create a branch, I would happily push the code changes to fix the typos.
![1-24-2020 10-56-13 AM](https://user-images.githubusercontent.com/35151114/73087564-4ca42b80-3e98-11ea-8294-a27130778879.png)

**Comment by apieniezny** [comment]
Thanks for catching those! I'll make the corrections.
